# Generated by Django 3.2 on 2023-04-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='esp2',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
